version: '2.1'

services:
  cityinfo-processor:
    container_name: cityinfo-processor
    image: cityinfo-processor:latest
    networks:
      - validator
      - rest-api
    depends_on:
      - validator
    volumes:
      - '.:/project/cityinfo/'

  cityinfo-client:
    container_name: cityinfo-client
    image: cityinfo-client:latest
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=rest-api,validator,${no_proxy}'
    volumes:
      - '.:/project/cityinfo/'
      - 'DataVolume1:/data'
    expose:
      - 8080
    ports:
      - '8080:8080'  # Expose the port 8080 for cityinfo-client
    networks:
      - city-sim
      - cityinfo-client
      - validator
      - rest-api

  nextjs-app:
    container_name: nextjs-app
    image: nextjs-app:latest
    command: npm run dev
    ports:
      - '3001:3001'
    networks:
      - city-sim
      - cityinfo-client
      - validator
      - rest-api
    depends_on:
      - cityinfo-client
    volumes:
      - 'DataVolume1:/data'

  sawtooth-rest-api:
    container_name: rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    networks:
      - validator
      - rest-api
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    networks:
      - validator
      - rest-api
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    container_name: validator
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    networks:
      - rest-api
      - validator
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "

  producer:
    container_name: producer
    image: producer:latest
    ports:
      - '5000:5000'
    networks:
      - city-sim
      - validator
      - rest-api

networks:
  city-sim:
    driver: bridge
  cityinfo-client:
    driver: bridge
  rest-api:
    driver: bridge
  validator:
    driver: bridge

volumes:
  DataVolume1:
